twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        matomo_url: '%env(default::MATOMO_URL)%'
        matomo_site_id: '%env(default::MATOMO_SITE_ID)%'

when@test:
    twig:
        strict_variables: true
